#!/usr/bin/bash

read -p "rootにログインします"
read -p "キーボードに日本語を選択します"
read -p "右上のタイム表示を右クリックし、プロパティでタイムゾーンを変更します"
read -p "terminalの背景を白にします"
read -p "エディタ(mousepad)の背景を白にし、Favoriteに追加します"
read -p "エディタ(gedit)の背景を白にし、Favoriteに追加します"
read -p "FirefoxとChromeをFavoriteに追加します"
read -p "Chromeの起動オプションに--no-sandboxを追加します"
read -p "default applicationにFirefoxを指定します"
read -p "Settings>Power Manger>Securityタブからスクリーンセーバーを非有効化します"
read -p "Firefoxのブラウザアドオンを導入します Foxy Proxy/Wappalyzer"
read -p "Burpの証明書をFirefoxに設定します"
read -p "Github、TryHackMeのログイン情報を登録します"
